# -------------------------------------------------------------------------------------
# Menu Configuration | 菜单配置
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "documentation"
  name = "Docs"
  url = "/categories/documentation/"
  title = "Theme Documentation"
  weight = 1
  [main.params]
    icon = "fa-regular fa-newspaper"

[[main]]
  identifier = "tests"
  name = "Tests"
  url = "tests/"
  title = "Tests for FixIt"
  weight = 3
  [main.params]
    draft = true
    icon = "fa-solid fa-flask text-success"

[[main]]
  identifier = "archives"
  name = "Archives"
  url = "archives/"
  weight = 10
  [main.params]
    icon = "fa-solid fa-archive"
[[main]]
  identifier = "categories"
  parent = "archives"
  name = "Categories"
  url = "categories/"
  weight = 11
  [main.params]
    icon = "fa-solid fa-folder-tree"
[[main]]
  identifier = "collections"
  parent = "archives"
  name = "Collections"
  url = "collections/"
  weight = 12
  [main.params]
    icon = "fa-solid fa-layer-group"
[[main]]
  identifier = "tags"
  parent = "archives"
  name = "Tags"
  url = "tags/"
  weight = 13
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "about"
  name = "About"
  url = "about/"
  weight = 20
  [main.params]
    icon = "fa-solid fa-signature"
[[main]]
  identifier = "releases"
  parent = "about"
  name = "Releases"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-xs text-secondary"></i>'
  url = "https://github.com/hugo-fixit/FixIt/releases"
  weight = 21
  [main.params]
    icon = "fa-solid fa-code-branch"
[[main]]
  identifier = "community"
  parent = "about"
  name = "Community"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-xs text-secondary"></i>'
  url = "https://github.com/hugo-fixit/FixIt/discussions"
  weight = 22
  [main.params]
    icon = "fa-regular fa-comments"
[[main]]
  identifier = "guides"
  parent = "about"
  name = "Guides"
  url = "guides/"
  weight = 23
  [main.params]
    icon = "fa-regular fa-compass"
[[main]]
  identifier = "components"
  parent = "about"
  name = "Components"
  url = "components/"
  weight = 24
  [main.params]
    icon = "fa-solid fa-puzzle-piece"
[[main]]
  identifier = "showcase"
  parent = "about"
  name = "Showcase"
  url = "showcase/"
  weight = 25
  [main.params]
    icon = "fa-solid fa-blog"
[[main]]
  identifier = "references"
  parent = "about"
  name = "References"
  url = "references/overview/"
  weight = 26
  [main.params]
    icon = "fa-solid fa-microchip"

[[main]]
  identifier = "github"
  pre = "<i class='fa-brands fa-github fa-fw' aria-hidden='true'></i>"
  url = "https://github.com/hugo-fixit/FixIt"
  title = "GitHub"
  weight = 100
  [main.params]
    class = "text-center"
    type = "mobile"
