# -------------------------------------------------------------------------------------
# Menu Configuration | 菜单配置
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "documentation"
  name = "Docs"
  url = "/documentation/"
  title = "Theme Documentation"
  weight = 1
  [main.params]
    icon = "fa-regular fa-newspaper"
[[main]]
  identifier = "guides"
  parent = "documentation"
  name = "Guides"
  url = "guides/"
  weight = 2
  [main.params]
    icon = "fa-regular fa-compass"
[[main]]
  identifier = "references"
  parent = "documentation"
  name = "References"
  url = "references/"
  weight = 3
  [main.params]
    icon = "fa-solid fa-microchip"
[[main]]
  identifier = "contributing"
  parent = "documentation"
  name = "Contributing"
  title = "Contribute to the FixIt project"
  url = "contributing/overview/"
  weight = 4
  [main.params]
    icon = "fa-solid fa-heart-circle-bolt text-danger fa-beat"
    # class = "fa-bounce"
[[main]]
  identifier = "releases"
  parent = "documentation"
  name = "Releases"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-xs text-secondary"></i>'
  url = "https://github.com/hugo-fixit/FixIt/releases"
  weight = 5
  [main.params]
    icon = "fa-solid fa-code-branch"
[[main]]
  identifier = "archives"
  parent = "documentation"
  name = "Archives"
  url = "archives/"
  weight = 20
  [main.params]
    icon = "fa-solid fa-archive"
    divided = true
[[main]]
  identifier = "categories"
  parent = "documentation"
  name = "Categories"
  url = "categories/"
  weight = 21
  [main.params]
    icon = "fa-solid fa-folder-tree"
[[main]]
  identifier = "collections"
  parent = "documentation"
  name = "Collections"
  url = "collections/"
  weight = 22
  [main.params]
    icon = "fa-solid fa-layer-group"
[[main]]
  identifier = "tags"
  parent = "documentation"
  name = "Tags"
  url = "tags/"
  weight = 23
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "components"
  name = "Components"
  title = "Hugo FixIt Components"
  url = "components/"
  weight = 30
  [main.params]
    icon = "fa-solid fa-puzzle-piece"

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase/"
  weight = 31
  [main.params]
    icon = "fa-solid fa-blog"

# TODO 新增 Community 页面（Hugo FixIt README、讨论、QQ 群、知识星球），开启评论
[[main]]
  identifier = "community"
  name = "Community"
  post = '<i class="fa-solid fa-external-link-alt fa-fw fa-xs text-secondary"></i>'
  url = "https://github.com/hugo-fixit/FixIt/discussions"
  weight = 40
  [main.params]
    icon = "fa-regular fa-comments"

[[main]]
  identifier = "tests"
  name = "Tests"
  url = "tests/"
  title = "Tests for FixIt"
  weight = 90
  [main.params]
    draft = true
    icon = "fa-solid fa-flask text-success"

[[main]]
  identifier = "github"
  pre = "<i class='fa-brands fa-github fa-fw' aria-hidden='true'></i>"
  url = "https://github.com/hugo-fixit/FixIt"
  title = "GitHub"
  weight = 100
  [main.params]
    class = "text-center"
    type = "mobile"
