# -------------------------------------------------------------------------------------
# Menu Configuration | 菜单配置
# See: https://fixit.lruihao.cn/theme-documentation-basics/#menu-advanced-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "documentation"
  name = "Docs"
  url = "documentation/"
  title = "Theme Documentation"
  weight = 1
  [main.params]
    icon = "fa-solid fa-book"

[[main]]
  identifier = "faqs"
  name = "FAQ"
  url = "faqs/"
  weight = 2
  [main.params]
    icon = "fa-solid fa-fire"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts/"
  weight = 10
  parent = ""
  [main.params]
    icon = "fa-solid fa-archive"
[[main]]
  identifier = "categories"
  name = "Categories"
  url = "categories/"
  weight = 11
  parent = "posts"
  [main.params]
    icon = "fa-solid fa-th"
[[main]]
  identifier = "tags"
  name = "Tags"
  url = "tags/"
  weight = 12
  parent = "posts"
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "about"
  name = "About"
  url = "about/"
  weight = 20
  [main.params]
    icon = "fa-solid fa-info-circle"
[[main]]
  identifier = "friends"
  name = "Friends"
  url = "friends/"
  weight = 21
  parent = "about"
  [main.params]
    icon = "fa-solid fa-users"
[[main]]
  identifier = "guides"
  name = "Guides"
  url = "guides/"
  weight = 22
  parent = "about"
  [main.params]
    icon = "fa-solid fa-layer-group"
[[main]]
  identifier = "references"
  name = "References"
  url = "references/"
  weight = 23
  parent = "about"
  [main.params]
    icon = "fa-solid fa-microchip"
[[main]]
  identifier = "tests"
  name = "Tests"
  url = "tests/"
  title = "Tests for FixIt"
  weight = 29
  parent = "about"
  [main.params]
    draft = true
    icon = "fa-solid fa-flask"

[[main]]
  identifier = "github"
  pre = "<i class='fa-brands fa-github fa-fw' aria-hidden='true'></i>"
  url = "https://github.com/hugo-fixit/FixIt"
  title = "GitHub"
  weight = 100
  [main.params]
    class = "text-center"
    type = "mobile"
