# -------------------------------------------------------------------------------------
# Theme Core Configuration | 主题核心配置
# See: https://fixit.lruihao.cn/zh-cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

description = "一个简洁、优雅且高效的 Hugo 主题 FixIt"

[gitInfo]
  dir = "content/zh-cn"

[search]
  [search.algolia]
    index = "index.zh-cn"

[home]
  [home.profile]
    subtitle = "一个简洁、优雅且高效的 Hugo 主题"

[social]
  GitHub = "hugo-fixit"
  Weibo = "liahao"
  Email = "fixit@lruihao.cn"
  RSS = true
  [social.QQGroup]
    id = "awbwdTtSQ_-H5QGzeJxdWgv6JMbNehNM"
    Title = "FixIt 主题交流群"

[pangu]
  enable = true
  selector = "article"

[watermark]
  content = '<img class="fixit-icon" src="/images/hugo-fixit.webp" alt="FixIt logo" /> FixIt 主题'

[githubCorner]
  title = "在 GitHub 上查看源代码"

