# -------------------------------------------------------------------------------------
# Theme Core Configuration | 主题核心配置
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[gitInfo]
  dir = "content/en"

[search]
  [search.algolia]
    index = "index.en"

[home]
  [home.profile]
    subtitle = "A Clean, Elegant but Advanced Hugo Theme"

[social]
  GitHub = "hugo-fixit"
  Twitter = "lruihao"
  Email = "fixit@lruihao.cn"
  RSS = true
  [social.QQGroup]
    id = "awbwdTtSQ_-H5QGzeJxdWgv6JMbNehNM"
    Title = "Join FixIt related discussion on QQ Group"

[watermark]
  content = '<img class="fixit-icon" src="/images/hugo-fixit.webp" alt="FixIt logo" /> FixIt Theme'