# -------------------------------------------------------------------------------------
# Taxonomies Configuration | 分类法配置
# See: https://gohugo.io/content-management/taxonomies/#configure-taxonomies
# -------------------------------------------------------------------------------------

# series = "series"
category = "categories"
tag = "tags"
collections = "collections"
