# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# FixIt 0.2.15 | NEW Developer options
# Configure with environment variable HUGO_PARAMS_GHTOKEN=xxx, see https://gohugo.io/functions/os/getenv/#examples
[dev]
  enable = false
  # Check for updates
  c4u = true
  # Mobile Devtools config
  [dev.mDevtools]
    enable = false
    # "vConsole", "eruda" supported
    type = "vConsole"
